### ISSUE TITLE
Nice Work！When will the code be released？

### ISSUE THREAD

**Issue by wslgqq277g** [Jiang-HB/DiffusionReg#1]

**Comment by sysuyl** [comment]
Also looking forward to that :)

**Comment by wslgqq277g** [comment]
Thanku for reply！ Can I have a copy of Appendix pdf? I'd like to dive into the derivation of this work.


Best wishes,
Linrui Gong


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Jiang-HB/DiffusionReg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月30日(星期一) 晚上7:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Jiang-HB/DiffusionReg] Nice Work！When will the code be released？ (Issue #1)





 
Hi,
 
Thank you for your attention. I plan to release the code after completing the upcoming CVPR submission.
 
Best wishes,
 Haobo

**Comment by Jiang-HB** [comment]
Certainly. Could you please provide me with your email address? I will send it to you shortly.

Best,
Haobo

**Comment by Andyliu7081** [comment]
Amazing work, inspiring to the field! When will the code be released?

**Comment by Jiang-HB** [comment]
Thank you for your interest. The code publication is currently in its final processing stage and is set to be released in the upcoming days (within almost 3 days).&nbsp;


Best wishes,
Haobo

&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Wed, Dec 20, 2023 03:30 AM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [Jiang-HB/DiffusionReg] Nice Work！When will the code be released？ (Issue #1)

&nbsp;



 
Amazing work, inspiring to the field! When will the code be released?
