### ISSUE TITLE
Open source license?

### ISSUE THREAD

**Issue by ajensen1234** [Jiang-HB/DiffusionReg#10]
Hi! I'm wondering if there is meant to be an open-source license for this repo, or if this was intentionally not included. Great job on the code. Thanks!

**Comment by Jiang-HB** [comment]
Hi,

The omission of an open-source license was not intentional. I have added a suitable open-source license to the repository shortly to ensure clear guidelines for usage and contribution.

Thank you for bringing this to my attention!

Best regards,
Haobo
